# Generated by Django 4.2.8 on 2023-12-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishery', '0002_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
